# generated by 'xml2py'
# flags '-vcd mylib.xml -l /home/jadesoul/git/dev/jadesoulpp/apps/tests/learn_ctypes/mylib.so -o mylib.py'
from ctypes import *

_libraries = {}
_libraries['/home/jadesoul/git/dev/jadesoulpp/apps/tests/learn_ctypes/mylib.so'] = CDLL('/home/jadesoul/git/dev/jadesoulpp/apps/tests/learn_ctypes/mylib.so')


# /home/jadesoul/git/dev/jadesoulpp/apps/tests/learn_ctypes/mylib.h 13
sum = _libraries['/home/jadesoul/git/dev/jadesoulpp/apps/tests/learn_ctypes/mylib.so'].sum
sum.restype = c_int
# sum(p1, p2)
sum.argtypes = [c_int, c_int]
sum.__doc__ = \
"""int sum(int p1, int p2)
/home/jadesoul/git/dev/jadesoulpp/apps/tests/learn_ctypes/mylib.h:13"""
__all__ = ['sum']
